language: erlang
notifications:
  disabled: true
branches:
  only:
    - master
    - develop
    - 0.1.0
    - 0.1.1
    - 0.2
    - 0.2.1
    - 0.2.2
otp_release:
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R16B
  - R15B03
  - R15B02
  - R15B01
  - R15B

